version: '3'
services:
  web:
    build: .
    ports:
      - "5000:5000"
    environment:
      - MYSQL_HOST=db
      - MYSQL_USER=username
      - MYSQL_PASSWORD=password
      - MYSQL_DB=movie_search
    depends_on:
      - db

  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: movie_search
      MYSQL_USER: username
      MYSQL_PASSWORD: password
    ports:
      - "3307:3306"

